
language: python
python:
  - 3.8
services:
  - docker

install:
  - pip install -r requirements.txt # Install the Docker image dependencies

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # Login to dockerhub
  - curl https://cli-assets.heroku.com/install.sh | sh  # Install heroku
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_LOGIN" --password-stdin registry.heroku.com  # Login to registry.heroku.com

script:
  - python -m unittest tests/api_v1_test.py # Unit testing
  - docker build -t joffreybvn/flask-demo-api:v1 . # Build the Docker image
  - docker tag joffreybvn/flask-demo-api:v1 registry.heroku.com/$HEROKU_APP/web # Tag the image

deploy:
  provider: script
  script:
    docker push joffreybvn/flask-demo-api:v1; # Push to Docker Hub
    docker push registry.heroku.com/$HEROKU_APP/web; # Push to Heroku
    heroku container:release web --app $HEROKU_APP # Deploy on Heroku
  on:
    branch: master